# script:
#   - docker run -e CI=true USERNAME/docker-react npm run test -- --coverage
language: generic   
sudo: required
services:
  - docker

before_install:
  - docker build -t lukefitz1/docker-react -f Dockerfile.dev .

script:
  - docker run CI=true lukefitz1/docker-react npm run test -- --coverage